package com.beck.beck_demos.budget_app.data_fakes;

import com.beck.beck_demos.budget_app.iData.iBudgetDAO;
import com.beck.beck_demos.budget_app.models.Budget;
import com.beck.beck_demos.budget_app.models.Budget_VM;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

public class BudgetDAO_Fake  implements  iBudgetDAO{
  private List<Budget_VM> budgetVMs;
  public BudgetDAO_Fake(){
    budgetVMs = new ArrayList<>();
    Budget budget0 = new Budget("HRZjMFMWMBFvDQigpbvXrkROUwQsTMfAgIgS", "qKCdKSkh", "GxwWnGek", "ZtkxftgS", new Date(), 32.91, "yKVOnTCy", true, new Date(), new Date());
    Budget budget1 = new Budget("AEdncckxcNyGoTmgHkiIDkHHaQCWrWPCufOk", "qKCdKSkh", "LblkCUZk", "WxeCVVNx", new Date(), 64.82, "pvSfCSUG", true, new Date(), new Date());
    Budget budget2 = new Budget("FiQVkbeABJRHFiuOZPhONmZmvTsgywjNBHtZ", "qKCdKSkh", "hZScCgoF", "ZJmvAgWZ", new Date(), 13.61, "cRoIDgcR", true, new Date(), new Date());
    Budget budget3 = new Budget("eKFdgCmawgZPSnxceWeAaUekxPfQunqBorgH", "qKCdKSkh", "FQGenruB", "gubBZLYk", new Date(), 47.72, "dkyvEugk", false, new Date(), new Date());
    Budget budget4 = new Budget("VljiQUDPbYQKOlgKBnKxDLjhpaEvkSLOqOPN", "qKCdKSkh", "mIrWQDxB", "npPPSYRT", new Date(), 34.53, "iQMycKqF", true, new Date(), new Date());
    Budget budget5 = new Budget("RBrqIwCNKdVMlMswrZlrULfBpvIhQiJVtEME", "OUiDBwUA", "uekBvOGU", "pALnUwEL", new Date(), 60.3, "uWWwNfSa", false, new Date(), new Date());
    Budget budget6 = new Budget("dEvNChydYeYjVEDkylbvkIOqANUTYcxjlOaR", "WmFbXMNE", "UiGsgSxn", "yLdPyCZy", new Date(), 46.26, "uWWwNfSa", false, new Date(), new Date());
    Budget budget7 = new Budget("uAleOruiYDZZaFqSRXJnFlISQokpJrsyYuvV", "XESBuJBT", "cbUrhkMg", "rVubFKhM", new Date(), 26.85, "uWWwNfSa", false, new Date(), new Date());
    Budget budget8 = new Budget("qlJcGxgNAPRJHmlCZoyITisTlBubENxUtZPP", "wtrKXkxZ", "ntspgEUh", "YilLeRXK", new Date(), 24.29, "uWWwNfSa", true, new Date(), new Date());
    Budget budget9 = new Budget("wuwtqSMAhOasALACkOlNfgMfGKJNjousYQjv", "gZoBSLMn", "keaLgZOJ", "FkUahVjm", new Date(), 38.38, "uWWwNfSa", true, new Date(), new Date());
    Budget budget10 = new Budget("fpDalngvINQiCofNsoSIUdCQsctgvvMGvfJn", "jaqpOCRp", "DJRtEofS", "mYiTWYtD", new Date(), 11.94, "QTvcJKSY", false, new Date(), new Date());
    Budget budget11 = new Budget("NYWmKCeSJFQYnLAsCJcFFjCSIKUyygmtNrwy", "jaqpOCRp", "IDxHhGfj", "prbKHISf", new Date(), 37.59, "XAheTSVK", false, new Date(), new Date());
    Budget budget12 = new Budget("cRgZWfWFQhfwYCmINUeadqLvCjTbwqFSLLvA", "jaqpOCRp", "fxFWxCSN", "CVMvPNgG", new Date(), 61.91, "uQjUUKha", false, new Date(), new Date());
    Budget budget13 = new Budget("KfCorhyTHfhdXMTQWjvdjLPuMlcoVnhqHuMs", "jaqpOCRp", "jXBUBDCr", "MJXtYWdl", new Date(), 58.67, "yVGcGFKn", false, new Date(), new Date());
    Budget budget14 = new Budget("RuOiIMCybLtyvWEFSvplHRvKMRLssGmIlFiF", "jaqpOCRp", "qIDcsPno", "ZufwTQeA", new Date(), 68.67, "DpBJiEHq", true, new Date(), new Date());
    Budget budget15 = new Budget("NEjdAHtDnnHweHFjOdvANuIDTPLkmSfTvNeG", "cFnxOmqd", "XhLraNpn", "RfqiSBdi", new Date(), 63.55, "RVaMFghm", false, new Date(), new Date());
    Budget budget16 = new Budget("bfmCbomlhWpnCYhFHwmQqIjiDUnXhbHvxJLu", "QYghqAEL", "EjUDXRtE", "kUuPTZyT", new Date(), 69.79, "RVaMFghm", false, new Date(), new Date());
    Budget budget17 = new Budget("yHNZxdYUQPNqMoPfwtMiAgUSArsamnkMhooo", "yiAqZNsd", "ssGaEKxJ", "ajYUbapH", new Date(), 31.65, "RVaMFghm", true, new Date(), new Date());
    Budget budget18 = new Budget("WgItcPGHkeafyxCCfVqffkOjwnYKqoHvECTl", "LZFmjJAS", "EqglKwjv", "sXrSRhml", new Date(), 42.19, "RVaMFghm", true, new Date(), new Date());
    Budget budget19 = new Budget("OlvUTKCvxUGGtrJkiBLHaWVTmbokIgXfRVqT", "MbibDFpN", "XySLBZYV", "ExAXHNLY", new Date(), 12.43, "RVaMFghm", true, new Date(), new Date());
    Budget budget20 = new Budget("HxFsAmUMKOpsWLwXosDiYGwUtqEdLxERDTiD", "bSXSGScD", "GuDHNbJu", "xVZjKXhq", new Date(), 18.64, "GOHaDwqo", true, new Date(), new Date());
    Budget budget21 = new Budget("oHRTuGNkmmfdMLKVQxUAJVlEnTgGWKoKnSVn", "bSXSGScD", "ubBSRKDJ", "uYwCZdIC", new Date(), 49.01, "lPHlaeVc", false, new Date(), new Date());
    Budget budget22 = new Budget("CiyRccruIITjKBlgdOfZPkfoSBiVghFTfwfP", "bSXSGScD", "pXBseXfL", "KTjgRCJq", new Date(), 25.98, "bTVZmfOu", true, new Date(), new Date());
    Budget budget23 = new Budget("mbhcrTCwwAnQdgDuxiUeIMLBBjSOxrWPbyCt", "bSXSGScD", "jiQGHdvP", "xTZXvGeH", new Date(), 40.09, "ANdlpYGU", true, new Date(), new Date());
    Budget budget24 = new Budget("VFhXnDQdXxSCrqtXjfjQiWLqqPlbskZBbZaL", "bSXSGScD", "AIBDLafO", "KhvEWQQt", new Date(), 66.39, "LjUwLjIH", true, new Date(), new Date());
    Budget budget25 = new Budget("twfIIjgVkpDvRuEOCPGJchyhBHQuhjjeoLJS", "fiOeSqaB", "ATFXQPgZ", "GcMLZDFS", new Date(), 27.66, "WHBENFhO", true, new Date(), new Date());
    Budget budget26 = new Budget("LjChPvjthWeNvniLCNSPZISBVnwuQkZlXEvW", "XTQUihDw", "nnVXSdkb", "jgsHlxXe", new Date(), 21.68, "WHBENFhO", true, new Date(), new Date());
    Budget budget27 = new Budget("kEYexYAJlKBZmSUgkZIiwEcpvvDjqsgIFhGc", "YeJATeBO", "nIKGUIUb", "EMBTaxtf", new Date(), 22.59, "WHBENFhO", false, new Date(), new Date());
    Budget budget28 = new Budget("cWYXibfShnwSrBVvcHcBYsQDxPlCDnkolFhn", "ESktfMGX", "diGAiKij", "aDIUjRtQ", new Date(), 47.58, "WHBENFhO", false, new Date(), new Date());
    Budget budget29 = new Budget("VhVMmrYOJkSrFPFKCKeicZAUbUVITgGSYFBL", "qjPuIJwk", "flCVjIvI", "gvgAdXvG", new Date(), 58.93, "WHBENFhO", true, new Date(), new Date());
    Budget_VM Budget_VM0= new Budget_VM(budget0);
    Budget_VM Budget_VM1= new Budget_VM(budget1);
    Budget_VM Budget_VM2= new Budget_VM(budget2);
    Budget_VM Budget_VM3= new Budget_VM(budget3);
    Budget_VM Budget_VM4= new Budget_VM(budget4);
    Budget_VM Budget_VM5= new Budget_VM(budget5);
    Budget_VM Budget_VM6= new Budget_VM(budget6);
    Budget_VM Budget_VM7= new Budget_VM(budget7);
    Budget_VM Budget_VM8= new Budget_VM(budget8);
    Budget_VM Budget_VM9= new Budget_VM(budget9);
    Budget_VM Budget_VM10= new Budget_VM(budget10);
    Budget_VM Budget_VM11= new Budget_VM(budget11);
    Budget_VM Budget_VM12= new Budget_VM(budget12);
    Budget_VM Budget_VM13= new Budget_VM(budget13);
    Budget_VM Budget_VM14= new Budget_VM(budget14);
    Budget_VM Budget_VM15= new Budget_VM(budget15);
    Budget_VM Budget_VM16= new Budget_VM(budget16);
    Budget_VM Budget_VM17= new Budget_VM(budget17);
    Budget_VM Budget_VM18= new Budget_VM(budget18);
    Budget_VM Budget_VM19= new Budget_VM(budget19);
    Budget_VM Budget_VM20= new Budget_VM(budget20);
    Budget_VM Budget_VM21= new Budget_VM(budget21);
    Budget_VM Budget_VM22= new Budget_VM(budget22);
    Budget_VM Budget_VM23= new Budget_VM(budget23);
    Budget_VM Budget_VM24= new Budget_VM(budget24);
    Budget_VM Budget_VM25= new Budget_VM(budget25);
    Budget_VM Budget_VM26= new Budget_VM(budget26);
    Budget_VM Budget_VM27= new Budget_VM(budget27);
    Budget_VM Budget_VM28= new Budget_VM(budget28);
    Budget_VM Budget_VM29= new Budget_VM(budget29);
    budgetVMs.add(Budget_VM0);
    budgetVMs.add(Budget_VM1);
    budgetVMs.add(Budget_VM2);
    budgetVMs.add(Budget_VM3);
    budgetVMs.add(Budget_VM4);
    budgetVMs.add(Budget_VM5);
    budgetVMs.add(Budget_VM6);
    budgetVMs.add(Budget_VM7);
    budgetVMs.add(Budget_VM8);
    budgetVMs.add(Budget_VM9);
    budgetVMs.add(Budget_VM10);
    budgetVMs.add(Budget_VM11);
    budgetVMs.add(Budget_VM12);
    budgetVMs.add(Budget_VM13);
    budgetVMs.add(Budget_VM14);
    budgetVMs.add(Budget_VM15);
    budgetVMs.add(Budget_VM16);
    budgetVMs.add(Budget_VM17);
    budgetVMs.add(Budget_VM18);
    budgetVMs.add(Budget_VM19);
    budgetVMs.add(Budget_VM20);
    budgetVMs.add(Budget_VM21);
    budgetVMs.add(Budget_VM22);
    budgetVMs.add(Budget_VM23);
    budgetVMs.add(Budget_VM24);
    budgetVMs.add(Budget_VM25);
    budgetVMs.add(Budget_VM26);
    budgetVMs.add(Budget_VM27);
    budgetVMs.add(Budget_VM28);
    budgetVMs.add(Budget_VM29);
    Collections.sort(budgetVMs);
  }
}
